source "https://rubygems.org"

ruby "3.3.0"

# Framework
gem "rails", "~> 8.1.0"

# Banco de dados
gem "pg", "~> 1.5"

# Servidor web
gem "puma", ">= 5.0"

# JSON (API)
gem "jbuilder"

# Senha segura
gem "bcrypt", "~> 3.1.7"

# Autenticação JWT
gem "jwt"

# CORS (frontend React)
gem "rack-cors"

# Upload de imagem
gem "image_processing", "~> 1.2"

# Logs mais limpos (produção)
gem "lograge"

group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "brakeman", require: false
  gem "bundler-audit", require: false
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end